### ISSUE TITLE
[v9] Eliminate `new User()` in favor of `$app->make(User::class)`

### ISSUE THREAD

**Issue by KorvinSzanto** [buttress/concrete5_codestyle_wg#4]
`new User()` does new work each time returning a new instance fetched newly from the database. By switching everywhere to `$app->make(User::class)`, we can make the current user instance a singleton and eliminate a lot of unnecessary cpu and io load.

**Comment by Ruudt** [comment]
Good idea.

While we're changing the way to fetch the user, perhaps we can also make this easier to read. I don't think `$app->make(User::class)` is really clear as to what exactly you'd get from it. What form could the call take, so it becomes clear that it returns the active/current user?

_p.s. I see Andrew added an instance of this way to get the current user 3 months ago._

**Comment by KorvinSzanto** [comment]
@Ruud-Zuiderlicht I'd agree that it's not immediately obvious that you're getting some "logged in user" but that's not what exactly is happening here. `$app->make(User::class)` is returning *the user* object, of which there is only ever one per request.

I could get behind a factory like `$user = $app->users()->current();`, but it'd be a harder sell to get people to start using instead of `new User` whereas the `$app->make(User::class)` is a drop-in replacement

**Comment by hissy** [comment]
Merged https://github.com/concrete5/concrete5/pull/7434

**Comment by mlocati** [comment]
Yep, this issue can be closed IMHO
